# Generated by Django 5.2.17 on 2026-09-24 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academic_period_report_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount_ars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('onboarding_amount_ars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(choices=[('onboarding', 'Alta pendiente'), ('trial', 'Piloto'), ('active', 'Activa'), ('suspended', 'Suspendida')], default='trial', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatformPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_on', models.DateField(unique=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('effective_on',),
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.CharField(choices=[('all', 'Todos'), ('students', 'Alumnos'), ('guardians', 'Familias'), ('teachers', 'Docentes'), ('staff', 'Personal')], default='all', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.school')),
            ],
            options={
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Alta pendiente de pago'), ('active', 'Activa'), ('canceled', 'Cancelada')], default='pending', max_length=16)),
                ('monthly_amount_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('onboarding_amount_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact_name', models.CharField(max_length=180)),
                ('contact_email', models.EmailField(max_length=254)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.notice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to='core.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'user', 'read_at'], name='core_notice_school__d926e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'notice', 'user'), name='unique_notice_read_per_user')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('onboarding', 'Alta y capacitación'), ('monthly', 'Abono mensual')], max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_on', models.DateField()),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('void', 'Anulado')], default='pending', max_length=12)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('transfer_reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.schoolsubscription')),
            ],
            options={
                'ordering': ('due_on', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'onboarding')), fields=('subscription', 'kind'), name='unique_onboarding_charge'), models.UniqueConstraint(condition=models.Q(('kind', 'monthly')), fields=('subscription', 'kind', 'period_start'), name='unique_monthly_charge_period')],
            },
        ),
    ]
