# Generated by Django 5.2.17 on 2026-09-26 22:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSignupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('email_pending', 'Verificación pendiente'), ('verified', 'Verificada'), ('converted', 'Convertida en escuela'), ('rejected', 'Rechazada')], default='email_pending', max_length=20)),
                ('school_name', models.CharField(max_length=180)),
                ('school_type', models.CharField(choices=[('common', 'Secundaria común'), ('technical', 'Técnica')], max_length=20)),
                ('jurisdiction', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(max_length=180)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone', models.CharField(max_length=40)),
                ('plan', models.CharField(choices=[('basic', 'Básico'), ('pro', 'Pro')], max_length=12)),
                ('monthly_quote_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('onboarding_quote_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote_expires_at', models.DateTimeField()),
                ('verification_token_hash', models.CharField(max_length=64)),
                ('verification_expires_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ip_digest', models.CharField(db_index=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to='core.school')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_school_signup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['state', 'expires_at'], name='core_school_state_e04337_idx'), models.Index(fields=['contact_email', 'created_at'], name='core_school_contact_e32182_idx')],
            },
        ),
    ]
