from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from core.forms import NexoPasswordResetForm
from core import views

urlpatterns = [
    path("", views.home, name="home"),
    path("registro/", views.school_signup_page, name="school_signup"),
    path("registro/verificar/<uuid:request_id>/<str:token>/", views.school_signup_verify, name="school_signup_verify"),
    path("registro/solicitud/<uuid:request_id>/", views.school_signup_result, name="school_signup_result"),
    path("plataforma/", views.platform_admin, name="platform_admin"),
    path("healthz/", views.api_health, name="healthz"),
    path("admin/", admin.site.urls),
    path("accounts/password_reset/", auth_views.PasswordResetView.as_view(
        template_name="core/password_reset_form.html", form_class=NexoPasswordResetForm,
        email_template_name="core/password_reset_email.txt",
        subject_template_name="core/password_reset_subject.txt", success_url="/accounts/password_reset/done/"), name="password_reset"),
    path("accounts/password_reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="core/password_reset_done.html"), name="password_reset_done"),
    path("accounts/reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="core/password_reset_confirm.html", success_url="/accounts/reset/done/"), name="password_reset_confirm"),
    path("accounts/reset/done/", views.password_reset_complete, name="password_reset_complete"),
    path("api/v1/auth/login/", views.api_login, name="api_login"),
    path("api/v1/auth/logout/", views.api_logout, name="api_logout"),
    path("api/v1/me/", views.api_me, name="api_me"),
    path("api/v1/schools/", views.api_schools, name="api_schools"),
    path("api/v1/schools/<int:school_id>/state/", views.platform_school_state, name="platform_school_state"),
    path("api/v1/platform/schools/<int:school_id>/subscription/", views.platform_school_subscription, name="platform_school_subscription"),
    path("api/v1/platform/schools/<int:school_id>/invite/", views.platform_resend_school_invite, name="platform_resend_school_invite"),
    path("api/v1/platform/schools/", views.platform_school_admin, name="platform_schools"),
    path("api/v1/public/school-signups/", views.school_signup_submit, name="public_school_signups"),
    path("api/v1/platform/school-signups/", views.platform_school_signup_requests, name="platform_school_signups"),
    path("api/v1/platform/school-signups/<uuid:request_id>/approve/", views.platform_school_signup_approve, name="platform_school_signup_approve"),
    path("api/v1/platform/school-signups/<uuid:request_id>/reject/", views.platform_school_signup_reject, name="platform_school_signup_reject"),
    path("api/v1/platform/school-signups/<uuid:request_id>/requote/", views.platform_school_signup_requote, name="platform_school_signup_requote"),
    path("api/v1/platform/billing/settings/", views.platform_billing_settings, name="platform_billing_settings"),
    path("api/v1/platform/billing/price-changes/", views.platform_schedule_price_change, name="platform_price_changes"),
    path("api/v1/platform/billing/charges/", views.platform_subscription_charges, name="platform_subscription_charges"),
    path("api/v1/platform/billing/charges/<int:charge_id>/", views.platform_subscription_charge_detail, name="platform_subscription_charge_detail"),
    path("api/v1/dashboard/", views.api_dashboard, name="api_dashboard"),
    path("api/v1/academic-followup/", views.api_academic_followup, name="api_academic_followup"),
    path("api/v1/analytics/academic/", views.api_academic_analytics, name="api_academic_analytics"),
    path("api/v1/students/", views.api_students, name="api_students"),
    path("api/v1/attendance/", views.api_attendance, name="api_attendance"),
    path("api/v1/grades/", views.api_grades, name="api_grades"),
    path("api/v1/report-cards/options/", views.api_report_card_options, name="api_report_card_options"),
    path("api/v1/report-cards/<int:student_id>/", views.api_report_card, name="api_report_card"),
    path("api/v1/books/", views.api_books, name="api_books"),
    path("api/v1/loans/", views.api_loans, name="api_loans"),
    path("api/v1/loans/<int:object_id>/", views.api_loans, name="api_loan_detail"),
    path("api/v1/lost/", views.api_lost, name="api_lost"),
    path("api/v1/claims/", views.api_claims, name="api_claims"),
    path("api/v1/claims/<int:object_id>/", views.api_claims, name="api_claim_detail"),
    path("api/v1/notices/", views.api_notices, name="api_notices"),
    path("api/v1/notices/<int:notice_id>/read/", views.api_notice_read, name="api_notice_read"),
    path("api/v1/events/", views.api_events, name="api_events"),
    path("api/v1/events/<int:event_id>/", views.api_events, name="api_event_detail"),
    path("api/v1/academic-options/", views.api_academic_options, name="api_academic_options"),
    path("api/v1/settings/", views.api_settings, name="api_settings"),
    path("api/v1/audit/", views.api_audit, name="api_audit"),
    path("api/v1/academic-plans/", views.api_plans, name="api_plans"),
    path("api/v1/plan-years/", views.api_plan_years, name="api_plan_years"),
    path("api/v1/sections/", views.api_sections, name="api_sections"),
    path("api/v1/enrollments/", views.api_enrollments, name="api_enrollments"),
    path("api/v1/offerings/", views.api_offerings, name="api_offerings"),
    path("api/v1/imports/preview/", views.api_import_preview, name="api_import_preview"),
    path("api/v1/imports/templates/", views.api_import_template, name="api_import_template"),
    path("api/v1/imports/<uuid:token>/commit/", views.api_import_commit, name="api_import_commit"),
    path("api/v1/exports/<str:resource>/", views.api_export, name="api_export"),
]
